// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// IUserUsecase is an autogenerated mock type for the IUserUsecase type
type IUserUsecase struct {
	mock.Mock
}

type IUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserUsecase) EXPECT() *IUserUsecase_Expecter {
	return &IUserUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, user
func (_m *IUserUsecase) Login(ctx context.Context, user *domain.User) (string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type IUserUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *IUserUsecase_Expecter) Login(ctx interface{}, user interface{}) *IUserUsecase_Login_Call {
	return &IUserUsecase_Login_Call{Call: _e.mock.On("Login", ctx, user)}
}

func (_c *IUserUsecase_Login_Call) Run(run func(ctx context.Context, user *domain.User)) *IUserUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *IUserUsecase_Login_Call) Return(_a0 string, _a1 error) *IUserUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserUsecase_Login_Call) RunAndReturn(run func(context.Context, *domain.User) (string, error)) *IUserUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, user
func (_m *IUserUsecase) Register(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUserUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IUserUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *IUserUsecase_Expecter) Register(ctx interface{}, user interface{}) *IUserUsecase_Register_Call {
	return &IUserUsecase_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *IUserUsecase_Register_Call) Run(run func(ctx context.Context, user *domain.User)) *IUserUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *IUserUsecase_Register_Call) Return(_a0 error) *IUserUsecase_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUserUsecase_Register_Call) RunAndReturn(run func(context.Context, *domain.User) error) *IUserUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUserUsecase creates a new instance of IUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserUsecase {
	mock := &IUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
